Add all widgets
andydotxyz/fynebuilder pull request #10
Opened 2021-02-14 14:55 UTC by aayush420

#4 This will be a continuous PR. Will be adding widgets one by one. 
[x] Check Box
[x] Radio 
[ ] Combo
...

2021-02-15 09:29 UTC, andydotxyz commented
Great progress thanks.
For the list above, I don't think that FormItem is a widget - more a property of form.
And PopUp/ModalPopUp/PopUpMenu are overlays so may not be possible/sensible to add at this stage.

2021-02-21 16:06 UTC, andydotxyz requested changes
This is so cool.
Just a minor change requested.

I also noticed that the new MultiLineEntry property fields don't seem to be multiline - but I cannot figure out why (try editing the text of a MultiLineEntry) - have you noticed this as well?

2021-02-21 16:06 UTC, andydotxyz commented on widget.go
> +			initialOption := widget.NewSelect(s.Options, func(opt string) { s.SetSelected(opt) })
This needs to support "(Select one)" which is the default - it shows as expected to start with but then is no longer available if you select an option.

2021-02-21 16:43 UTC, aayush420 commented
> This is so cool.
> Just a minor change requested.
> 
> I also noticed that the new MultiLineEntry property fields don't seem to be multiline - but I cannot figure out why (try editing the text of a MultiLineEntry) - have you noticed this as well?

Yeah I did, and it's a bit weird. Also, the name on the properties palette is shown as `Entry` instead of `MultiLineEntry`. This might be happening because of the fact that I'm accessing the Entry object from the CanvasObject `obj` in here - 
![image](https://user-images.githubusercontent.com/16898783/108631836-f0904a00-7491-11eb-8529-d845595fc6ab.png)

2021-02-21 17:05 UTC, aayush420 commented
> > This is so cool.
> > Just a minor change requested.
> > I also noticed that the new MultiLineEntry property fields don't seem to be multiline - but I cannot figure out why (try editing the text of a MultiLineEntry) - have you noticed this as well?
> 
> Yeah I did, and it's a bit weird. Also, the name on the properties palette is shown as `Entry` instead of `MultiLineEntry`. This might be happening because of the fact that I'm accessing the Entry object from the CanvasObject `obj` in here -
> ![image](https://user-images.githubusercontent.com/16898783/108631836-f0904a00-7491-11eb-8529-d845595fc6ab.png)

Just found out that doing `mle := obj.(*widget.Entry)` has caused the properties to come from the original entry's properties. Need to figure out a way to reference `MultiLineEntry`, but it isn't defined by widget.

2021-02-21 17:10 UTC, aayush420 commented
> 
> Just found out that doing `mle := obj.(*widget.Entry)` has caused the properties to come from the original entry's properties. Need to figure out a way to reference `MultiLineEntry`, but it isn't defined by widget.

The same problem is there with passwordEntry's properties palette too (as this was also called as `*widget.Entry`).

2021-02-21 18:19 UTC, aayush420 commented
> The same problem is there with passwordEntry's properties palette too (as this was also called as `*widget.Entry`).

Fixed this by patching the `choose` method to have special cases for `PasswordEntry` and `MultiLineEntry`

2021-02-21 19:36 UTC, andydotxyz approved these changes
Amazing thanks

2021-02-21 19:37 UTC, merged