Search box for widget palette
andydotxyz/fynebuilder pull request #12
Opened 2021-02-21 05:45 UTC by aayush420

2021-02-21 16:14 UTC, andydotxyz requested changes
Excellent, though some of the code is a little strange - suggested improvement inline

2021-02-21 16:14 UTC, andydotxyz commented on main.go
> +	searchBox.SetText(" ")
This looks like a bit of a workaround - why not set it up correctly to start:

```diff
diff --git a/main.go b/main.go
index 42bc4c3..e42d59d 100644
--- a/main.go
+++ b/main.go
@@ -26,6 +26,7 @@ func buildLibrary() fyne.CanvasObject {
        widgetLowerNames := []string{}
        for _, name := range widgetNames {
                widgetLowerNames = append(widgetLowerNames, strings.ToLower(name))
+               tempNames = append(tempNames, name)
        }
        list := widget.NewList(func() int {
                return len(tempNames)
@@ -52,8 +53,6 @@ func buildLibrary() fyne.CanvasObject {
                }
                list.Refresh()
        }
-       searchBox.SetText(" ")
-       searchBox.SetText("")
 
        return container.NewBorder(searchBox, widget.NewButtonWithIcon("Insert", theme.ContentAddIcon(), func() {
                if c, ok := current.(*overlayContainer); ok {
```

2021-02-21 19:40 UTC, andydotxyz requested changes
This code looks great and runs well. 
However:
* If you select an item in the pallete
* search for something else
* new items get selected
* add item to a container
* - notice that different item (the old one) is added.

This may be caused by a bug in list, I'm not sure. If that is the case then we should de-select the list item before updating it's display...

2021-02-22 18:34 UTC, andydotxyz commented
Please don't force-push after a review has been added. It means we lose all the context and have to start again.

2021-02-25 02:59 UTC, aayush420 commented
> Please don't force-push after a review has been added. It means we lose all the context and have to start again.

I was just trying to rebase the branch on the latest HEAD from main.

2021-02-25 08:51 UTC, andydotxyz commented
> I was just trying to rebase the branch on the latest HEAD from main.

You should not rebase public branches (especially when attached to a PR) - it rewrites history. Use merge instead.

2021-02-27 19:07 UTC, andydotxyz requested changes
Almost! It now does not have the strange issue, but when nothing is selected it remembers the previous selection - which because of this code is sometimes not what you would think.
I think this should be resolved by adding:

```go
	list.OnUnselected = func(widget.ListItemID) {
		selected = nil
	}
```

2021-03-01 09:59 UTC, andydotxyz approved these changes
Great new feature, thanks

2021-03-01 09:59 UTC, merged